var questions = [
  [
    {
      question: "Which animal is the king of jungle?",
      option1: "Tiger",
      option2: "Elephant",
      option3: "Zebra",
      option4: "Lion",
      ans: "option4",
    },
    {
      question: "National bird of India?",
      option1: "Crow",
      option2: "Pigeon",
      option3: "Peacock",
      option4: "Hen",
      ans: "option3",
    },
    {
      question: "Which fruit is the king of fruits",
      option1: "Mango",
      option2: "Apple",
      option3: "Pineapple",
      option4: "Orange",
      ans: "option1",
    },
    {
      question: "Which is the longest animal?",
      option1: "Elephant",
      option2: "Tiger",
      option3: "Hippo",
      option4: "Giraffe",
      ans: "option4",
    },
    {
      question: "Which animal can fly?",
      option1: "Snake",
      option2: "Bat",
      option3: "Tortoise",
      option4: "Frog",
      ans: "option2",
    },
    {
      question: "Who is the Father of Nation?",
      option1: "Mahatma Gandhi",
      option2: "Pandit Jawarhalal Nehru",
      option3: "Dr APJ Abdul Kalam",
      option4: "Subhash Chandra Bose",
      ans: "option1",
    },
    {
      question: "Who is the missile man of India?",
      option1: "Mahatma Gandhi",
      option2: "Pandit Jawarhalal Nehru",
      option3: "Dr APJ Abdul Kalam",
      option4: "Subhash Chandra Bose",
      ans: "option3",
    },
    {
      question: "Who founded the Azad army?",
      option1: "Mahatma Gandhi",
      option2: "Pandit Jawarhalal Nehru",
      option3: "Dr APJ Abdul Kalam",
      option4: "Subhash Chandra Bose",
      ans: "option4",
    },
    {
      question: "Which fruit has seeds outside",
      option1: "Mango",
      option2: "Watermelon",
      option3: "Banana",
      option4: "Strawberry",
      ans: "option4",
    },
    {
      question: "Fastest animal?",
      option1: "Cheetah",
      option2: "Tiger",
      option3: "Panther",
      option4: "Lion",
      ans: "option1",
    },
  ],
  [
    {
      question: "Inside which HTML element do we put the JavaScript?",
      option1: "<head>",
      option2: "<body>",
      option3: "<html>",
      option4: "<script>",
      ans: "option4",
    },
    {
      question: "Inside which HTML element do we put the CSS?",
      option1: "<h1>",
      option2: "<body>",
      option3: "<Link href rel='stylesheet'>",
      option4: "<script>",
      ans: "option3",
    },
    {
      question: "Full form of HTML?",
      option1: "<Hypertext markup language>",
      option2: "<Hello tello mello language>",
      option3: "<Hpertext makeup language>",
      option4: "<script>",
      ans: "option1",
    },
    {
      question: "Which is a Framwork of Javascript",
      option1: "Django",
      option2: "Express",
      option3: "Flask",
      option4: "Laravel",
      ans: "option2",
    },
    {
      question: "Which of the following is the backend framework of JavaScript?",
      option1: "React js",
      option2: "Angular js",
      option3: "Vue js",
      option4: "Express js",
      ans: "option4",
    },
    {
      question: "Which library is maintained by facebook?",
      option1: "React js",
      option2: "Express js",
      option3: "Angular js",
      option4: "Vue js",
      ans: "option1",
    },
    {
      question: "How to declare a constant variable in javascript?",
      option1: "var",
      option2: "let",
      option3: "const",
      option4: "constant",
      ans: "option3",
    },
    {
      question: "In which year Javascript was invented?",
      option1: "1995",
      option2: "1996",
      option3: "1997",
      option4: "1994",
      ans: "option1",
    },
    {
      question: "Who invented Javascript?",
      option1: "Guido van Rossum",
      option2: "Brendan Eich",
      option3: "James Gosling OC",
      option4: "Rasmus Lerdorf",
      ans: "option2",
    },
    {
      question: "Which of the following is not used in the frontend of a website?",
      option1: "Javascript",
      option2: "HTML",
      option3: "CSS",
      option4: "JAVA",
      ans: "option4",
    },
  ],
  [
    {
      question: "Who discovered gravity?",
      option1: "Albert Einstein",
      option2: "Issac Newton",
      option3: "Thomas Edison",
      option4: "Linus Pauling",
      ans: "option2",
    },
    {
      question: "What is the formula of Force?",
      option1: "F=m*a",
      option2: "F=P/A",
      option3: "F=a*a",
      option4: "F=g/a",
      ans: "option1",
    },
    {
      question: "What is the famous equation given by Albert Einstein?",
      option1: "F=m*a",
      option2: "E=m*(c*c)",
      option3: "F = GMm r2",
      option4: "P=F/a",
      ans: "option2",
    },
    {
      question: "Formula of water?",
      option1: "H2O2",
      option2: "H3O",
      option3: "HCL",
      option4: "H2O",
      ans: "option4",
    },
    {
      question: "Formula of hrdrogen peroxide?",
      option1: "H2O2",
      option2: "H3O",
      option3: "HCL",
      option4: "H2O",
      ans: "option1",
    },
    {
      question: "Which acid is present in our stomach?",
      option1: "H2O2",
      option2: "H3O",
      option3: "HCL",
      option4: "H2O",
      ans: "option3",
    },
    {
      question: "Which organ helps us in respiration?",
      option1: "Kidney",
      option2: "Heart",
      option3: "Lungs",
      option4: "Liver",
      ans: "option3",
    },
    {
      question: "What is the work of Heart?",
      option1: "To purify blood",
      option2: "To pump blood",
      option3: "To remove blood",
      option4: "To help in respiration",
      ans: "option2",
    },
    {
      question: "Formula of Sulphuric acid?",
      option1: "HCL",
      option2: "CL2F2",
      option3: "H2SO4",
      option4: "H2O",
      ans: "option3",
    },
    {
      question: "What is the full form of HCL?",
      option1: "Hydro chloric acid",
      option2: "Sulphuric acid",
      option3: "Hydrogen chloride",
      option4: "Hydrogen peroxide",
      ans: "option3",
    },
  ],
  [
    {
      question: "Who is the considered as the first person of India?",
      option1: "Prime Minister",
      option2: "Home minister",
      option3: "President",
      option4: "Health Minister",
      ans: "option3",
    },
    {
      question: "Under which minister health sector falls?",
      option1: "Prime Minister",
      option2: "Home minister",
      option3: "President",
      option4: "Health Minister",
      ans: "option4",
    },
    {
      question: "Who manages Internal security and Border of Nation?",
      option1: "Prime Minister",
      option2: "Home minister",
      option3: "President",
      option4: "Health Minister",
      ans: "option2",
    },
    {
      question: "Who is most powerful among these 4?",
      option1: "Prime Minister",
      option2: "Home minister",
      option3: "President",
      option4: "Health Minister",
      ans: "option1",
    },
    {
      question: "What is contained in article 1 of Indian Constitution?",
      option1: "Union and its states",
      option2: "Citizenship",
      option3: "Fundamental Rights",
      option4: "DPSP's",
      ans: "option1",
    },
    {
      question: "Which part of Indian constitution describes about Panchayats?",
      option1: "Part I",
      option2: "Part X",
      option3: "Part V",
      option4: "Part IX",
      ans: "option4",
    },
    {
      question: "Which part of Indian constitution describes about the Union?",
      option1: "Part I",
      option2: "Part X",
      option3: "Part V",
      option4: "Part IX",
      ans: "option3",
    },
    {
      question: "Which part of Indian constitution describes about the Elections?",
      option1: "Part I",
      option2: "Part XV",
      option3: "Part V",
      option4: "Part IX",
      ans: "option2",
    },
    {
      question: "Which part of Indian constitution describes about the Official languages?",
      option1: "Part I",
      option2: "Part XVII",
      option3: "Part V",
      option4: "Part IX",
      ans: "option2",
    },
    {
      question: "Who is known as the Father of Indian Constituion?",
      option1: "Dr Bhimrao Ambedkar",
      option2: "Mahatma Gandhi",
      option3: "Dr APJ Abdul Kalam",
      option4: "Pandit Jawarhalal Nehru",
      ans: "option1",
    },
  ],
];

export default questions;
